os:
  - 'linux'
  - 'osx'
sudo: false
matrix:
  include:
    - os: 'windows'
      env: 'BIN_EXT=.exe'
      go: '1.10'
    - os: 'windows'
      env: 'BIN_EXT=.exe'
      go: '1.11'

language: 'go'
go:
  - '1.10'
  - '1.11'

install:
  - 'cd $GOPATH'
  - 'if [ "$(go version | awk ''{print $3}'')" == "go1.10" ]; then go get -u golang.org/x/vgo && BIN=vgo; else BIN=go; fi'
  - 'mv ${TRAVIS_BUILD_DIR} ${TRAVIS_HOME}/test'
  - 'cd ${TRAVIS_HOME}/test'
script:
  - '${BIN} build -o testdata/fatal/fatal${BIN_EXT} testdata/fatal/fatal.go'
  - '${BIN} build -o testdata/fatalf/fatalf${BIN_EXT} testdata/fatalf/fatalf.go'
  - '${BIN} build -o testdata/fatalln/fatalln${BIN_EXT} testdata/fatalln/fatalln.go'
  - '${BIN} test -v -race -count=10'
