os:
  - 'linux'
  - 'osx'
sudo: false

language: 'go'
go:
  - '1.10'
  - '1.11'
  - 'tip'

env:
  - 'GOBIN=go'
install:
  - 'cd $GOPATH'
  - 'if [ "$(go version | awk ''{print $3}'')" == "go1.10" ]; then go get -u golang.org/x/vgo && GOBIN=vgo; fi'
  - 'mkdir $HOME/test'
  - 'rsync -az $TRAVIS_BUILD_DIR/ $HOME/test/'
  # remove the project from GOPATH to mirror real use case
  - 'rm -rf $TRAVIS_BUILD_DIR'
  - 'cd $HOME/test'
script:
  - '$GOBIN build -o testdata/fatal/fatal testdata/fatal/fatal.go'
  - '$GOBIN build -o testdata/fatalf/fatalf testdata/fatalf/fatalf.go'
  - '$GOBIN build -o testdata/fatalln/fatalln testdata/fatalln/fatalln.go'
  - '$GOBIN test -v -race -count=10'
