os:
  - 'linux'
  - 'osx'
sudo: false

language: 'go'
go:
  - '1.10'
  - '1.11'
  - 'tip'

env:
  - 'BIN=go'
  - 'GOVERSION=$(go version | awk ''{print $3}'')'
install:
  - 'if [ "$GOVERSION" == "go1.10" ]; then go get -u golang.org/x/vgo && BIN=vgo; fi'
  - 'mkdir $HOME/test'
  - 'rsync -az $TRAVIS_BUILD_DIR/ $HOME/test/'
  # remove the project from GOPATH to mirror real use case
  - 'rm -rf $TRAVIS_BUILD_DIR'
  - 'cd $HOME/test'
script:
  - '$BIN build -o testdata/fatal/fatal testdata/fatal/fatal.go'
  - '$BIN build -o testdata/fatalf/fatalf testdata/fatalf/fatalf.go'
  - '$BIN build -o testdata/fatalln/fatalln testdata/fatalln/fatalln.go'
  - '$BIN test -v -race -count=10'
